<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
   <modelVersion>4.0.0</modelVersion>
   <groupId>com.example</groupId>
   <artifactId>application</artifactId>
   <version>1.0-SNAPSHOT</version>
   <packaging>pom</packaging>
   <name>face application</name>

   <modules>
      <module>module-ejb</module>
      <module>module-ejb1</module>
      <module>module-ejb2</module>
      <module>module-ejb3</module>
      <module>module-ejb4</module>
      <module>module-ejb5</module>
      <module>module-ejb6</module>
      <module>module-ejb7</module>
      <module>module-ejb8</module>
      <module>module-ejb9</module>
      <module>module-ejb10</module>
      <module>module-ejb11</module>
      <module>module-ejb12</module>
      <module>module-ejb13</module>
      <module>module-ejb14</module>
      <module>module-ejb15</module>
      <module>module-ejb16</module>
      <module>module-ejb17</module>
      <module>module-ejb18</module>
      <module>module-ejb19</module>
      <module>module-ejb20</module>
      <module>module-ejb21</module>
      <module>module-ejb22</module>
      <module>module-ejb23</module>
      <module>module-ejb24</module>
      <module>module-ejb25</module>
      <module>module-ejb26</module>
      <module>module-ejb27</module>
      <module>module-ejb28</module>
      <module>module-ejb29</module>
      <module>module-ejb30</module>
      <module>module-ejb31</module>
      <module>module-ejb32</module>
      <module>module-ejb33</module>
      <module>module-ejb34</module>
      <module>module-ejb35</module>
      <module>module-ejb36</module>
      <module>module-ejb37</module>
      <module>module-ejb38</module>
      <module>module-ejb39</module>
      <module>module-ejb40</module>
      <module>module-ejb41</module>
      <module>module-ejb42</module>
      <module>module-ejb43</module>
      <module>module-ejb44</module>
      <module>module-ejb45</module>
      <module>module-ejb46</module>
      <module>module-ejb47</module>
      <module>module-ejb48</module>
      <module>module-ejb49</module>
      <module>module-ejb50</module>
      <module>module-ejb51</module>
      <module>module-ejb52</module>
      <module>module-ejb53</module>
      <module>module-ejb54</module>
      <module>module-ejb55</module>
      <module>module-ejb56</module>
      <module>module-ejb57</module>
      <module>module-ejb58</module>
      <module>module-ejb59</module>
      <module>module-ejb60</module>
      <module>module-ejb61</module>
      <module>module-ejb62</module>
      <module>module-ejb63</module>
      <module>module-ejb64</module>
      <module>module-ejb65</module>
      <module>module-ejb66</module>
      <module>module-ejb67</module>
      <module>module-ejb68</module>
      <module>module-ejb69</module>
      <module>module-ejb70</module>
      <module>module-ejb71</module>
      <module>module-ejb72</module>
      <module>module-ejb73</module>
      <module>module-ejb74</module>
      <module>module-ejb75</module>
      <module>module-ejb76</module>
      <module>module-ejb77</module>
      <module>module-ejb78</module>
      <module>module-ejb79</module>
      <module>module-ejb80</module>
      <module>module-ejb81</module>
      <module>module-ejb82</module>
      <module>module-ejb83</module>
      <module>module-ejb84</module>
      <module>module-ejb85</module>
      <module>module-ejb86</module>
      <module>module-ejb87</module>
      <module>module-ejb88</module>
      <module>module-ejb89</module>
      <module>module-ejb90</module>
      <module>module-ejb91</module>
      <module>module-ejb92</module>
      <module>module-ejb93</module>
      <module>module-ejb94</module>
      <module>module-ejb95</module>
      <module>module-ejb96</module>
      <module>module-ejb97</module>
      <module>module-ejb98</module>
      <module>module-ejb99</module>
      <module>module-ejb100</module>
      <module>module-ejb101</module>
      <module>module-ejb102</module>
      <module>module-ejb103</module>
      <module>module-ejb104</module>
      <module>module-ejb105</module>
      <module>module-ejb106</module>
      <module>module-ejb107</module>
      <module>module-ejb108</module>
      <module>module-ejb109</module>
      <module>module-ejb110</module>
      <module>module-ejb111</module>
      <module>module-ejb112</module>
      <module>module-ejb113</module>
      <module>module-ejb114</module>
      <module>module-ejb115</module>
      <module>module-ejb116</module>
      <module>module-ejb117</module>
      <module>module-ejb118</module>
      <module>module-ejb119</module>
      <module>module-ejb120</module>
      <module>module-ejb121</module>
      <module>module-ejb122</module>
      <module>module-ejb123</module>
      <module>module-ejb124</module>
      <module>module-ejb125</module>
      <module>module-ejb126</module>
      <module>module-ejb127</module>
      <module>module-ejb128</module>
      <module>module-ejb129</module>
      <module>module-ejb130</module>
      <module>module-ejb131</module>
      <module>module-ejb132</module>
      <module>module-ejb133</module>
      <module>module-ejb134</module>
      <module>module-ejb135</module>
      <module>module-ejb136</module>
      <module>module-ejb137</module>
      <module>module-ejb138</module>
      <module>module-ejb139</module>
      <module>module-ejb140</module>
      <module>module-ejb141</module>
      <module>module-ejb142</module>
      <module>module-ejb143</module>
      <module>module-ejb144</module>
      <module>module-ejb145</module>
      <module>module-ejb146</module>
      <module>module-ejb147</module>
      <module>module-ejb148</module>
      <module>module-ejb149</module>
      <module>module-ejb150</module>
      <module>module-ejb151</module>
      <module>module-ejb152</module>
      <module>module-ejb153</module>
      <module>module-ejb154</module>
      <module>module-ejb155</module>
      <module>module-ejb156</module>
      <module>module-ejb157</module>
      <module>module-ejb158</module>
      <module>module-ejb159</module>
      <module>module-ejb160</module>
      <module>module-ejb161</module>
      <module>module-ejb162</module>
      <module>module-ejb163</module>
      <module>module-ejb164</module>
      <module>module-ejb165</module>
      <module>module-ejb166</module>
      <module>module-ejb167</module>
      <module>module-ejb168</module>
      <module>module-ejb169</module>
      <module>module-ejb170</module>
      <module>module-ejb171</module>
      <module>module-ejb172</module>
      <module>module-ejb173</module>
      <module>module-ejb174</module>
      <module>module-ejb175</module>
      <module>module-ejb176</module>
      <module>module-ejb177</module>
      <module>module-web</module>
      <module>module-ear</module>
   </modules>

   <properties>
      <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
   </properties>

   <dependencyManagement>
      <dependencies>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb1</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb2</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb3</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb4</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb5</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb6</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb7</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb8</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb9</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb10</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb11</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb12</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb13</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb14</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb15</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb16</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb17</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb18</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb19</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb20</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb21</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb22</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb23</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb24</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb25</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb26</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb27</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb28</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb29</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb30</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb31</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb32</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb33</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb34</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb35</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb36</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb37</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb38</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb39</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb40</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb41</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb42</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb43</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb44</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb45</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb46</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb47</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb48</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb49</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb50</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb51</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb52</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb53</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb54</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb55</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb56</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb57</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb58</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb59</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb60</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb61</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb62</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb63</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb64</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb65</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb66</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb67</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb68</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb69</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb70</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb71</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb72</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb73</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb74</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb75</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb76</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb77</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb78</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb79</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb80</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb81</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb82</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb83</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb84</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb85</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb86</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb87</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb88</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb89</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb90</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb91</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb92</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb93</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb94</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb95</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb96</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb97</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb98</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb99</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb100</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb101</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb102</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb103</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb104</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb105</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb106</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb107</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb108</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb109</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb110</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb111</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb112</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb113</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb114</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb115</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb116</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb117</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb118</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb119</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb120</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb121</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb122</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb123</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb124</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb125</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb126</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb127</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb128</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb129</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb130</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb131</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb132</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb133</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb134</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb135</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb136</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb137</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb138</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb139</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb140</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb141</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb142</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb143</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb144</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb145</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb146</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb147</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb148</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb149</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb150</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb151</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb152</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb153</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb154</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb155</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb156</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb157</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb158</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb159</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb160</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb161</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb162</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb163</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb164</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb165</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb166</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb167</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb168</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb169</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb170</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb171</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb172</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb173</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb174</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb175</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb176</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>
         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-ejb177</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>ejb</type>
         </dependency>

         <dependency>
            <groupId>com.example</groupId>
            <artifactId>application-web</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>war</type>
            <scope>compile</scope>
         </dependency>

         <dependency>
            <groupId>javax</groupId>
            <artifactId>javaee-api</artifactId>
            <version>7.0</version>
            <scope>provided</scope>
         </dependency>
         <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.8.2</version>
            <scope>test</scope>
         </dependency>


         <!-- https://mvnrepository.com/artifact/javax.servlet/javax.servlet-api -->
         <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>4.0.1</version>
            <scope>provided</scope>
         </dependency>

      </dependencies>
   </dependencyManagement>

   <build>
      <pluginManagement>
         <plugins>
            <plugin>
               <groupId>io.openliberty.tools</groupId>
               <artifactId>liberty-maven-plugin</artifactId>
               <version>3.11.3</version> <!-- Use your current plugin version -->
               <configuration>
                  <!-- Automatically sets scannable="false" for all your pom dependencies -->
                  <scanLibs>false</scanLibs>
               </configuration>
            </plugin>
            <plugin>
               <groupId>org.apache.maven.plugins</groupId>
               <artifactId>maven-compiler-plugin</artifactId>
               <version>3.9.0</version>
               <configuration>
                  <source>1.8</source>
                  <target>1.8</target>
               </configuration>
            </plugin>

            <plugin>
               <artifactId>maven-ejb-plugin</artifactId>
               <version>3.2.1</version>
               <configuration>
                  <ejbVersion>3.0</ejbVersion>
               </configuration>
            </plugin>

            <plugin>
               <groupId>org.apache.maven.plugins</groupId>
               <artifactId>maven-war-plugin</artifactId>
               <version>3.3.1</version>
            </plugin>

            <plugin>
               <groupId>org.apache.maven.plugins</groupId>
               <artifactId>maven-ear-plugin</artifactId>
               <version>3.3.0</version>

            </plugin>
         </plugins>
      </pluginManagement>
   </build>

   <profiles>
      <profile>
         <id>unpack</id>
         <build>
            <pluginManagement>
               <plugins>
                  <plugin>
                     <groupId>org.apache.maven.plugins</groupId>
                     <artifactId>maven-ear-plugin</artifactId>
                     <configuration>
                        <unpackTypes>war,ejb</unpackTypes>
                     </configuration>
                  </plugin>
               </plugins>
            </pluginManagement>
         </build>
      </profile>
   </profiles>

</project>