apiVersion: apps.openliberty.io/v1
kind: OpenLibertyApplication
metadata:
  name: maven-ear-example
  labels:
    name: maven-ear-example
spec:
  applicationImage: guide/maven-ear-example-imagestream:1.0-SNAPSHOT
  pullPolicy: Always
  service:
    port: 9443
  expose: true
  manageTLS: true
  env:
    - name: WLP_LOGGING_MESSAGE_FORMAT
      value: "json"
    - name: WLP_LOGGING_CONSOLE_LOGLEVEL
      value: "info"
    - name: WLP_LOGGING_MESSAGE_SOURCE
      value: "message,trace,accessLog,ffdc,audit"

