apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-ear-example-deployment
  labels:
    app: maven-ear-example
spec:
  selector:
    matchLabels:
      app: maven-ear-example
  template:
    metadata:
      labels:
        app: maven-ear-example
    spec:
      containers:
      - name: maven-ear-example-container
        image: image-registry.openshift-image-registry.svc:5000/demo-app-init-container/maven-ear-example
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: shared-volume
          mountPath: /var/www/app
      initContainers:
        - name: init-cont
          image: image-registry.openshift-image-registry.svc:5000/demo-app-init-container/maven-ear-example
          command: ["/bin/sh"]
          args: ["-c", "echo 'here' >/var/www/app/here.txt"]
          volumeMounts:
            - name: shared-volume
              mountPath: /var/www/app
      volumes:
        - name: shared-volume
          emptyDir: {}

--- 
apiVersion: v1
kind: Service
metadata:
  name: maven-ear-example-service
spec:
  selector:
    app: maven-ear-example
  ports:
  - protocol: TCP
    port: 9080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: maven-ear-example-route
spec:
  to:
    kind: Service
    name: maven-ear-example-service

